/**
 * createDate : 2016年7月26日下午3:08:57
 */
package cn.lastmiles.alipay.model.status.shop;

public enum CreateStatus {
	SUCCESS
	,
	SHOPCREATESYSTEMERROR
	,
	SHOPCREATEINVALIDPARAM
	,
	SHOPCREATEUNIQUECONSTRAINTSHOPERROR
	,
	SHOPCREATEUNIQUECONSTRAINTIMPLEMENTIDERROR
	,
	SHOPCREATEUNIQUECONSTRAINTOUTSHOPIDERROR
	,
	SHOPCREATECATOGORYNOTEXISTS
	,
	SHOPCREATESHOPJUDGEFAIL
	,
	SHOPCREATELICENSEEXPIRES
	,
	SHOPCREATECTUFAIL
	,
	LICENSEISREQUIRED
	,
	CERTIFICATEISREQUIRED
	,
	SHOPCATEGORYNOTMATCHCITY
	,
	BRANDCATEGORYNOTMATCH
	,
	IMPLEMENTIDINVALID
	,
	EXISTFORBIDDENWORD
	,
	MERCHANTNOTEXIST
	,
	LICENSECODEREPEATERROR
	,
	SHOPCREATELICENSEPRINCIPALNOTMATCH
	,
	SHOPCREATELOCATIONVALIDATEFAIL
}
